name: 'Notify Telegram'
description: 'Send notification to Telegram via n8n webhook'

inputs:
  webhook_url:
    description: 'Telegram webhook URL'
    required: true
  event:
    description: 'Event type (deploy_failed, build_failed, etc.)'
    required: true
  repository:
    description: 'Repository name'
    required: true
  actor:
    description: 'User who triggered the action'
    required: true
  run_url:
    description: 'URL to the workflow run'
    required: true
  version:
    description: 'Version number (optional)'
    required: false
    default: ''
  branch:
    description: 'Branch name (optional)'
    required: false
    default: ''
  commit:
    description: 'Commit SHA (optional)'
    required: false
    default: ''
  pr_number:
    description: 'Pull request number (optional)'
    required: false
    default: ''
  pr_title:
    description: 'Pull request title (optional)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Send Telegram notification
      shell: bash
      run: |
        # Build JSON payload dynamically
        JSON='{"event": "${{ inputs.event }}", "repository": "${{ inputs.repository }}", "actor": "${{ inputs.actor }}", "run_url": "${{ inputs.run_url }}"'

        if [ -n "${{ inputs.version }}" ]; then
          JSON="$JSON, \"version\": \"${{ inputs.version }}\""
        fi

        if [ -n "${{ inputs.branch }}" ]; then
          JSON="$JSON, \"branch\": \"${{ inputs.branch }}\""
        fi

        if [ -n "${{ inputs.commit }}" ]; then
          JSON="$JSON, \"commit\": \"${{ inputs.commit }}\""
        fi

        if [ -n "${{ inputs.pr_number }}" ]; then
          JSON="$JSON, \"pr_number\": \"${{ inputs.pr_number }}\""
        fi

        if [ -n "${{ inputs.pr_title }}" ]; then
          JSON="$JSON, \"pr_title\": \"${{ inputs.pr_title }}\""
        fi

        JSON="$JSON}"

        curl -k -X POST "${{ inputs.webhook_url }}" \
          -H "Content-Type: application/json" \
          -d "$JSON"
